backend:
  name: git-gateway
  branch: optimize #Branch to update (optional; defaults to master)

publish_mode: editorial_workflow

media_folder: "assets/images/uploads"
public_folder: "images/uploads"


collections:
  - name: "news" # Used in routes e.g. /admin/collections/news
    label: "News" # Used in the UI
    folder: "_posts/news" # the path to the folder where the documents are stored
    create: true # allow users to create new documents in this collection
    slug: "{{year}}-{{slug}}" # Filename template
    fields: # fields for each document in collection
      - {label: "Layout", name: "layout", widget: "hidden", default: "blog"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Featured Image", name: "thumbnail", widget: "image"}
      - {label: "Body", name: "body", widget: "markdown"}
