backend:
  name: git-gateway
  branch: optimize #Branch to update (optional; defaults to master)

publish_mode: editorial_workflow

media_folder: "assets/images/uploads"
public_folder: "images/uploads"

collections:
  - name: 'blog'
    label: 'Blog'
    folder: 'assets/content/blog'
    create: true
    format: 'json'
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    editor:
      preview: true
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Description', name: 'description', widget: 'string' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
  - name: 'speaker'
    label: 'Speakers'
    folder: 'assets/content/speakers'
    create: true
    format: 'json'
    slug: '{{title}}'
    editor: 
      preview: true
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Speaker Name', name: 'name', widget: 'string' }
      - { label: 'Bio', name: 'bio', widget: 'markdown' }
      - { label: 'Speaker Title', name: 'speakerTitle', widget: 'string' }
      - { label: 'Talk Title', name: 'talkTitle', widget: 'string' }
      - { label: 'Talk Description', name: 'talkDescription', widget: 'markdown' }
      - { label: 'Speaker Image', name: 'speakerImage', widget: 'file' }
